### ISSUE TITLE
can you add a centralized api_keys.conf file for adding ALL api keys in one location?

### ISSUE THREAD

**Issue by ashutosh771** [mr-rizwan-syed/chomtesh#15]
Hello Team,

Kindly see if you can add such a file so that users don't have to find config file for different tools. something like subfinder.

file contents should be as under..

shodan:[space]abcdeadsad
urlscan: testapikeyofurlscan
binaryedge: apikeygoeshere

**Comment by mr-rizwan-syed** [comment]
Hi Ashutosh,

We had made the required changes, 
Now we can utilize config.yml file to put API Key secrets at one location

currently below are supported, rest all needed to put in subfinder config file `~/.config/subfinder/provider-config.yaml`

```config.yml
SHODAN_API_KEY: [Y0UR-API-KEYES-G0ES-HERE]
URLSCAN_API_KEY: [Y0UR-API-KEYES-G0ES-HERE]
```
