### ISSUE TITLE
Workflow for building and pushing a docker image to DCR.

### ISSUE THREAD

**Issue by sahil-sagwekar2652** [mr-rizwan-syed/chomtesh#18]
The script requires many packages to be installed, which is unviable and cumbersome for someone trying to run the script for just once.

Although we have a Dockerfile, it would be great if users could pull down a ready-made image.

Btw, your talk at the FOSS Mumbai January meetup was great! :) Got to learn a lot.

**Comment by mr-rizwan-syed** [comment]
Thanks for checking out the tool bro,
We already have images on Docker Hub

`docker pull r12w4n/chomtesh`

Check out the README.MD For chomte.sh container usage.
 
Also we've setup  GitHub Actions to build and push the same.
